In [ ]:
'''
Author: Haihui Pan
Date: 2021-10-19
Ref: https://pytorch.org/tutorials/beginner/basics/data_tutorial.html
'''

# Tensor

## PyTorch简介

Torch是一个与Numpy类似的张量操作库，但是Torch可以支持GPU。Torch采用C语言作为底层，以Lua为上层接口的深度学习库。但是，由于Lua太小众化，因此才出现Pytorch。Pytorch使用与Torch相同的底层C语言库,但是上层的接口语言是Python。

Pytorch是一个基于Torch的深度学习框架，主要由Facebook的人工智能研究小组开发的。PyTorch主要提供两个强大的功能：
* 强大的GPU进行张量加速计算
* 神经网络自动求导机制

PyTorch优点：
* 面向对象设计简洁优雅，容易入门
* 有不错的技术文档，由Facebook进行维护

## Tensor的基本类型
Tensor的基本类型有5种：
* 16位整型：torch.short
* 32位整型：torch.int
* 64位整型：torch.long
* 32位浮点型：torch.float（默认）
* 64位浮点型：torch.double

除了数字类型外，还有byte和char类型

## Tensor初始化

In [1]:
#版本信息
import torch
torch.__version__

device="gpu" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [2]:
#从List进行初始化
a=[1,2,3]
print(torch.tensor(a))

tensor([1, 2, 3])


In [3]:
#从numpy初始化
import numpy as np

np_data=np.array(a)
np_data=torch.from_numpy(np_data)
np_data

tensor([1, 2, 3], dtype=torch.int32)

In [4]:
#随机初始化
x=torch.rand(2,3) #shape:(2,3)
x

tensor([[0.1291, 0.4987, 0.4681],
        [0.8987, 0.5599, 0.1569]])

In [5]:
#使用1来进行初始化
x=torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [6]:
#单位矩阵初始化
x=torch.eye(2,2)
x

tensor([[1., 0.],
        [0., 1.]])

## Tensor属性
* shape:形状
* dtype:类型
* device:数据是存放在CPU还是GPU

In [11]:
t=torch.rand(2,3,dtype=torch.float)
print("t shape:",t.shape)
print("t dtype:",t.dtype)
print("t device:",t.device)

t shape: torch.Size([2, 3])
t dtype: torch.float32
t device: cpu


## Tensor常见操作

* Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。

In [13]:
#转numpy
tensor=torch.eye(3,3)
np_tensor=tensor.numpy()
print(type(np_tensor),"\n",np_tensor)

<class 'numpy.ndarray'> 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#切片(与Numpy一致)
tensor=torch.eye(3,3)
print("第一行：",tensor[0])
print("第一列：",tensor[:,0])
print("最后一列：",tensor[:,-1])

tensor[:,0]=0
print(tensor)

第一行： tensor([1., 0., 0.])
第一列： tensor([1., 0., 0.])
最后一列： tensor([0., 0., 1.])
tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
# 取max
t=torch.rand(3,3)
print(t)
max_value,max_idx=torch.max(t,dim=0) #max(t[i][0]),max(t[i][1]),max(t[i][2]) ,由于每个t[i]都是3维，因此相当于是比较每一列的最大值
print("max of dim:0")
print(max_value)
print(max_idx)

print("max of dim:1")
max_value,max_idx=torch.max(t,dim=1) #max(t[0][i]),max(t[1][i]),max(t[2][i]) ,
print(max_value)
print(max_idx)

tensor([[0.5715, 0.9573, 0.0328],
        [0.2425, 0.7956, 0.5219],
        [0.6476, 0.5040, 0.2640]])
max of dim:0
tensor([0.6476, 0.9573, 0.5219])
tensor([2, 0, 1])
max of dim:1
tensor([0.9573, 0.7956, 0.6476])
tensor([1, 1, 0])


In [16]:
#sum中dim的取值与max为一致
t=[[1,1,1],
   [2,3,4],
   [3,3,3]]
t=torch.tensor(t)

#效果相当于列相加
print("sum by dim:0")
print(torch.sum(t,dim=0)) #sum(t[i])

#效果相当于行相加
print("sum by dim:1")
print(torch.sum(t,dim=1)) #sum(t[0][i]),sum(t[1][i]),sum(t[2][i]) 

sum by dim:0
tensor([6, 7, 8])
sum by dim:1
tensor([3, 9, 9])


## Tensor矩阵操作

In [17]:
#矩阵转置
a=[[1,2],
   [3,4]]
a=torch.tensor(a)
print(a.T)

tensor([[1, 3],
        [2, 4]])


In [18]:
# 矩阵相加
t1=torch.eye(3,3)
t2=torch.ones(3,3)

print(t1+t2) 

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])


In [19]:
# 矩阵相乘
t1=torch.ones(2,2)
t2=torch.ones(2,2)

#两种操作是等价
print(t1.matmul(t2))
print(t1@t2)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [20]:
#矩阵相对应的位置相乘(element-wise product)
t1=torch.ones(2,2)
t2=torch.ones(2,2)

#两种操作是等价的
print(t1*t2)
print(t1.mul(t2))

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


## Tensor矩阵shape变更

In [25]:
#view变换形状
t=torch.rand(4,4)
t=t.view(-1,2) #shape:(2,8)
print(t.shape)

torch.Size([8, 2])


In [26]:
#更换维度（2,3,4）-> (3,2,4)
t=torch.rand(2,3,4)
t=t.transpose(0,1) #更换dim=0和dim=1的维度
print(t.shape)

torch.Size([3, 2, 4])


In [31]:
# expand
t = torch.tensor([[1], [2], [3]]) #shape(3,1)
t=t.expand(-1,4) # shape(3,4)
t

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

## Tensor矩阵拼接

In [27]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1,2,3])

print(torch.cat([t1,t2],dim=0)) #[t[0],t[1]]

tensor([1, 2, 3, 1, 2, 3])


In [28]:
t1=torch.tensor([1,2,3])
t2=torch.tensor([1,2,3])

#扩充维度
t1=torch.unsqueeze(t1,dim=0)
t2=torch.unsqueeze(t2,dim=0)

print(torch.cat([t1,t2],dim=0))

tensor([[1, 2, 3],
        [1, 2, 3]])


In [29]:
t1=torch.eye(3,3)

#按列进行拼接，逻辑与max一致[t1[0],t1[1],t2[2],t1[0],t1[1],t2[2],t1[0],t1[1],t2[2]]
print(torch.cat([t1,t1,t1],dim=0))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [30]:
print(torch.cat([t1,t1,t1],dim=1)) #[t1[0]*3,t1[1]*3,t1[0]*3]

tensor([[1., 0., 0., 1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1., 0., 0., 1.]])
